[api]
# Your GTI API key
api_key = GTI_API_KEY
base_url = https://www.virustotal.com/api/v3

# Comma-separated list of threat list IDs
# Possible values : ransomware, malicious-network-infrastructure, malware, threat-actor, trending, mobile, osx, linux, iot, cryptominer, phishing, first-stage-delivery-vectors, vulnerability-weaponization, infostealer
threat_list_ids = ransomware, malicious-network-infrastructure, malware, threat-actor, trending, mobile, osx, linux, iot, cryptominer, phishing, first-stage-delivery-vectors, vulnerability-weaponization, infostealer
# Only fetch IOCs with the threat score above the following value (between 0 and 100)
threat_score =

[filters]
# Include IOCs with following comma-separated list of Severity Level(s).(leave blank for all)
# Possible values : SEVERITY_NONE,SEVERITY_LOW,SEVERITY_MEDIUM,SEVERITY_HIGH,SEVERITY_UNKNOWN
severity = SEVERITY_HIGH

# Include IOCs with following comma-separated list of Verdict Level(s).(leave blank for all)
# Possible values : VERDICT_BENIGN,VERDICT_UNDETECTED,VERDICT_SUSPICIOUS,VERDICT_MALICIOUS,VERDICT_UNKNOWN
verdict = VERDICT_SUSPICIOUS,VERDICT_MALICIOUS


[runtime]
# Lifetime of an IOC in days (after which it is removed from local JSON)
ioc_lifetime_days = 7
log_file = gti_sync.log
log_level = INFO

[files]
# Checkpoint file to store last execution timestamps per threat list
checkpoint_file = checkpoint.json
